name: Website-deploy-to-vps
'on':
  push:
    branches:
      - dev
jobs:
  run_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 18.x
    steps:
      - run: ls
      - run: cd ./LenelS2Dashboard/project-website
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
        with:
          node-version: '${{ matrix.node-version}}'
          cache: npm
      - run: |
            npm i
            npm run build
  run_client_deploy:
     runs-on: ubuntu-latest
     needs: run_build
     strategy:
      matrix:
        node-version:
          - 18.x
     steps:
        - run: cd project-website
        - name: Setup Node.js environment
          uses: actions/setup-node@v3.8.1
          with:
            node-version: '${{ matrix.node-version}}'
            cache: npm
        - run: npm i
        - run: npm run build
        - name: delete build and create new
          uses: appleboy/ssh-action@v1.0.0
          with:
           host: '${{ secrets.WEBSITE_HOST }}'
           username: '${{ secrets.SSH_USER }}'
           key: '${{ secrets.SSH_KEY }}'
           port: '${{ secrets.PORT }}'
           script: |
             cd /var/www/html
             rm -rf dist
             mkdir dist
           run: |
             cp -TR project-website/dist ../dist
             tar -cvzf deploy.tar.gz ../dist/
        - name: delete build and create new
          uses: appleboy/scp-action@v0.1.4
          with:
             host: '${{ secrets.WEBSITE_HOST }}'
             username: '${{ secrets.SSH_USER }}'
             key: '${{ secrets.SSH_KEY }}'
             port: '${{ secrets.PORT }}'
             source: deploy.tar.gz
             target: /var/www/html
        - name: delete build and create new
          uses: appleboy/ssh-action@v1.0.0
          with:
            host: '${{ secrets.WEBSITE_HOST }}'
            username: '${{ secrets.SSH_USER }}'
            key: '${{ secrets.SSH_KEY }}'
            port: '${{ secrets.PORT }}'
            script: |
               cd /var/www/html
               tar -xvzf deploy.tar.gz
               rm deploy.tar.gz
