name: Website-deploy-to-vps
'on':
  push:
    branches:
      - dev
jobs:
  run_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 16.x
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: dev 
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
        with:
          node-version: '${{ matrix.node-version}}'
          cache: npm
      - run: |
            npm i
            npm run build
  run_client_deploy:
     runs-on: ubuntu-latest
     needs: run_build
     strategy:
      matrix:
        node-version:
          - 16.x
     steps:
        - name: checkout
          uses: actions/checkout@v4
          with:
            ref: dev 
        - name: Setup Node.js environment
          uses: actions/setup-node@v3.8.1
          with:
            node-version: '${{ matrix.node-version}}'
            cache: npm
        - run: |
              npm i
              npm run build
        - name: ssh and create directory for fs
          uses: appleboy/ssh-action@v1.0.0
          with:
           host: '${{ secrets.WEBSITE_HOST }}'
           username: '${{ secrets.SSH_USER }}'
           password: '${{ secrets.SSH_KEY }}'
           port: '${{ secrets.PORT }}'
           script: |
             cd /var/www/html
             rm -rf dist
             mkdir dist
        - run: |
             cp -TR ./dist ../dist
             cp -TR ./website-files/ ../dist
             tar -cvzf deploy.tar.gz ../dist/
        - name: scp actions to the server
          uses: appleboy/scp-action@v0.1.4
          with:
             host: '${{ secrets.WEBSITE_HOST }}'
             username: '${{ secrets.SSH_USER }}'
             password: '${{ secrets.SSH_KEY }}'
             port: '${{ secrets.PORT }}'
             source: deploy.tar.gz
             target: /var/www/html
        - name: delete previous tar
          uses: appleboy/ssh-action@v1.0.0
          with:
            host: '${{ secrets.WEBSITE_HOST }}'
            username: '${{ secrets.SSH_USER }}'
            password: '${{ secrets.SSH_KEY }}'
            port: '${{ secrets.PORT }}'
            script: |
               cd /var/www/html
               tar -xvzf deploy.tar.gz
               rm deploy.tar.gz
